use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ToolCategory {
    TokenCompression,
    BrowserStealth,
    ApiGateway,
    PromptObfuscation,
    ProxyInfrastructure,
    IdentityMasking,
    SwarmOrchestration,
    Monetization,
    OffensiveCyber,
    ProxyIp,
    Ipv6Blocks,
    SshRemoteDesktop,
    ServerManagement,
    AiProviderIntegration,
    CommunicationPlatform,
    McpSkills,
    Infrastructure,
    SearchEngine,
    ContentFetching,
    EmbeddingsVectorDb,
    MemoryGraph,
    LocalModels,
    AgentOrchestration,
    RagEngine,
    ReferenceUi,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ToolSource {
    Pip,
    Npm,
    Docker,
    Binary,
    Rust,
    Mcp,
    BuiltIn,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolConfig {
    pub id: String,
    pub name: String,
    pub category: ToolCategory,
    pub source: ToolSource,
    pub install_cmd: Option<String>,
    pub run_cmd: Option<String>,
    pub health_check_url: Option<String>,
    pub port: Option<u16>,
    pub enabled: bool,
    pub installed: bool,
    pub description: String,
    pub version: String,
    pub homepage: String,
}

#[allow(clippy::too_many_arguments)]
fn tc(
    id: &str, name: &str, cat: ToolCategory, src: ToolSource,
    install: Option<&str>, run: Option<&str>, health: Option<&str>,
    port: Option<u16>, desc: &str, ver: &str, home: &str,
) -> ToolConfig {
    ToolConfig {
        id: id.to_string(), name: name.to_string(), category: cat, source: src,
        install_cmd: install.map(String::from), run_cmd: run.map(String::from),
        health_check_url: health.map(String::from), port,
        enabled: false, installed: false,
        description: desc.to_string(), version: ver.to_string(), homepage: home.to_string(),
    }
}

pub fn all_tool_configs() -> Vec<ToolConfig> {
    vec![
        // ===== TOKEN COMPRESSION (9) =====
        tc("leanctx", "leanctx", ToolCategory::TokenCompression, ToolSource::Pip,
            Some("pip install leanctx"), Some("leanctx"), None, None,
            "Real-time prompt compression. Reduces token bills by 40-60% via LLMLingua-2.", "0.2.0",
            "https://github.com/your/leanctx"),
        tc("twotrim", "TwoTrim", ToolCategory::TokenCompression, ToolSource::Pip,
            Some("pip install twotrim"), Some("twotrim"), None, None,
            "Lightweight prompt compression. Up to 65% token reduction without accuracy loss.", "1.0.0",
            "https://github.com/overseek944/twotrim"),
        tc("tokenpress", "TokenPress", ToolCategory::TokenCompression, ToolSource::Pip,
            Some("pip install tokenpress"), Some("tokenpress"), None, None,
            "Ultra-fast LLM token compressor in Rust. 2-5x fewer tokens, same output quality.", "0.3.0",
            "https://github.com/your/tokenpress"),
        tc("token-compressor-mcp", "Token Compressor MCP", ToolCategory::TokenCompression, ToolSource::Pip,
            Some("pip install token-compressor-mcp"), Some("token-compressor-mcp"), None, None,
            "Semantic prompt compression for LLM workflows. 40-60% reduction without meaning loss.", "0.1.0",
            "https://github.com/your/token-compressor-mcp"),
        tc("vibeflow", "VibeFlow", ToolCategory::TokenCompression, ToolSource::Pip,
            Some("pip install vibeflow"), Some("vibeflow"), None, None,
            "High-performance context optimizer. Up to 70% LLM token reduction.", "0.1.0",
            "https://github.com/alperensu/VibeFlow"),
        tc("late-cli", "late-cli", ToolCategory::TokenCompression, ToolSource::Pip,
            Some("pip install late-cli"), Some("late-cli"), None, None,
            "AI coding agent with ephemeral context. Zero token bloat, saves up to 10k tokens.", "0.1.0",
            "https://github.com/mlhher/late-cli"),
        tc("icm-graph", "icm-graph", ToolCategory::TokenCompression, ToolSource::Binary,
            Some("pip install icm-graph"), Some("icm-graph"), None, None,
            "Single binary. Cuts AI coding costs 70-90%. Memory + knowledge graph + semantic compression.", "0.1.0",
            "https://github.com/ncmonx/icm-graph"),
        tc("winnow-compress", "winnow-compress", ToolCategory::TokenCompression, ToolSource::Pip,
            Some("pip install winnow-compress"), Some("winnow-compress"), None, None,
            "Sits between vector DB and LLM. Compresses retrieved context ~50% with <3% accuracy loss.", "0.1.0",
            "https://github.com/your/winnow-compress"),
        tc("omniroute-compress", "OmniRoute (Compression)", ToolCategory::TokenCompression, ToolSource::Docker,
            Some("docker pull diegosouzapw/omniroute"), Some("docker run -p 8088:8088 diegosouzapw/omniroute"),
            Some("http://localhost:8088/health"), Some(8088),
            "Built-in prompt compression in OmniRoute gateway. Saves 15-75% tokens.", "1.0.0",
            "https://github.com/diegosouzapw/omniroute"),

        // ===== BROWSER STEALTH (14) =====
        tc("cloakbrowser", "CloakBrowser", ToolCategory::BrowserStealth, ToolSource::Npm,
            Some("npm install cloakbrowser"), Some("npx cloakbrowser"), None, None,
            "Stealth Chromium with 49+ C++ patches. Passes 30/30 bot detection tests.", "1.0.0",
            "https://github.com/your/cloakbrowser"),
        tc("camoufox", "Camoufox Browser Server", ToolCategory::BrowserStealth, ToolSource::Npm,
            Some("npm install camoufox"), Some("npx camoufox"), None, None,
            "Stealth browser server for AI agents. C++-level Firefox fork with fingerprint spoofing.", "1.0.0",
            "https://github.com/redf0x1/camofox-browser"),
        tc("invisible-playwright", "invisible_playwright", ToolCategory::BrowserStealth, ToolSource::Npm,
            Some("npm install invisible_playwright"), Some("npx invisible_playwright"), None, None,
            "Modified Firefox 150 + Playwright wrapper. Passes reCAPTCHA v3 + FingerprintPro at C++ level.", "1.0.0",
            "https://github.com/feder-cr/invisible_playwright"),
        tc("botbrowser", "BotBrowser", ToolCategory::BrowserStealth, ToolSource::Npm,
            Some("npm install botbrowser"), Some("npx botbrowser"), None, None,
            "Advanced privacy browser kernel. Defeats Cloudflare, Akamai, Kasada, DataDome, hCaptcha.", "1.0.0",
            "https://github.com/botswin/BotBrowser"),
        tc("obscura", "Obscura", ToolCategory::BrowserStealth, ToolSource::Rust,
            None, None, None, None,
            "Lightweight Headless browser in Rust. 30MB memory. Stealth mode for AI agents.", "0.1.0",
            "https://github.com/h4ckf0r0day/obscura"),
        tc("mcp-stealth-chrome", "MCP Stealth Chrome", ToolCategory::BrowserStealth, ToolSource::Pip,
            Some("pip install mcp-stealth-chrome"), Some("uvx mcp-stealth-chrome"),
            None, None,
            "MCP server with 133 tools. Bypass Cloudflare Turnstile in 1 line. TLS fingerprint masking.", "0.4.11",
            "https://github.com/RobithYusuf/mcp-stealth-chrome"),
        tc("zendriver-mcp", "ZenDriver MCP Server", ToolCategory::BrowserStealth, ToolSource::Pip,
            Some("pip install zendriver-mcp"), Some("uvx zendriver-mcp"), None, None,
            "Undetectable browser automation via CDP. Bot detection bypass, 96+ tools.", "1.0.0",
            "https://github.com/bituq/zendriver-mcp"),
        tc("wick-mcp", "Wick MCP", ToolCategory::BrowserStealth, ToolSource::Npm,
            Some("npm install -g wick-mcp"), Some("wick-mcp"), None, None,
            "MCP server using real Chrome network stack (Cronet). TLS fingerprint matches real browser. Linux/macOS only.", "1.0.0",
            "https://github.com/wickproject/wick"),
        tc("openchrome", "openchrome", ToolCategory::BrowserStealth, ToolSource::Mcp,
            Some("npx openchrome"), Some("npx openchrome"), None, None,
            "Open-source browser automation MCP. Controls real Chrome via CDP with 27 intelligent subsystems.", "1.0.0",
            "https://github.com/shaun0927/openchrome"),
        tc("byob", "BYOB", ToolCategory::BrowserStealth, ToolSource::Mcp,
            Some("npx byob"), Some("npx byob"), None, None,
            "Local MCP server. Lets AI coding tools control your real logged-in Chrome directly.", "1.0.0",
            "https://github.com/wxtsky/byob"),
        tc("puppeteer-fingerprints", "puppeteer-with-fingerprints", ToolCategory::BrowserStealth, ToolSource::Npm,
            Some("npm install puppeteer-with-fingerprints"), Some("npx puppeteer-with-fingerprints"), None, None,
            "Puppeteer plugin for changing browser fingerprint and generating virtual identity.", "1.0.0",
            "https://github.com/your/puppeteer-fingerprints"),
        tc("fingerprint-suite", "fingerprint-suite", ToolCategory::BrowserStealth, ToolSource::Npm,
            Some("npm install fingerprint-generator fingerprint-injector"), None, None, None,
            "Modular toolkit for realistic browser fingerprints. Inject into Playwright/Puppeteer.", "1.0.0",
            "https://github.com/your/fingerprint-suite"),

        // ===== API GATEWAY (9) =====
        tc("omniroute", "OmniRoute", ToolCategory::ApiGateway, ToolSource::Docker,
            Some("docker pull diegosouzapw/omniroute"), Some("docker run -p 8088:8088 diegosouzapw/omniroute"),
            Some("http://localhost:8088/health"), Some(8088),
            "Most powerful open-source AI gateway. 160+ providers, 13 routing strategies, auto failover.", "1.0.0",
            "https://github.com/diegosouzapw/omniroute"),
        tc("smarter-router", "SmarterRouter", ToolCategory::ApiGateway, ToolSource::Pip,
            Some("pip install smarter-router"), Some("smarter-router"), None, None,
            "Smart multi-backend router. Ollama, llama.cpp, OpenAI with semantic caching and failover.", "1.0.0",
            "https://github.com/peva3/SmarterRouter"),
        tc("freerouter", "FreeRouter", ToolCategory::ApiGateway, ToolSource::Pip,
            Some("pip install freerouter"), Some("freerouter"), None, None,
            "Self-hosted OpenRouter alternative. Classifies requests across 14 dimenions, routes automatically.", "1.0.0",
            "https://github.com/openfreerouter/freerouter"),
        tc("plexus", "Plexus", ToolCategory::ApiGateway, ToolSource::Docker,
            Some("docker pull mcowger/plexus"), Some("docker run -p 8080:8080 mcowger/plexus"),
            Some("http://localhost:8080/health"), Some(8080),
            "Unified API gateway for OpenAI, Anthropic, Google, GitHub Copilot. OAuth, quotas, embeddings.", "1.0.0",
            "https://github.com/mcowger/plexus"),
        tc("lunargate", "LunarGate", ToolCategory::ApiGateway, ToolSource::Binary,
            Some("go install github.com/lunargate-ai/gateway@latest"), None, None, None,
            "High-performance AI gateway in Go. OpenAI-compatible API, Ollama support, failover.", "1.0.0",
            "https://github.com/lunargate-ai/gateway"),
        tc("ferro-gateway", "Ferro Labs AI Gateway", ToolCategory::ApiGateway, ToolSource::Binary,
            Some("go install github.com/ferro-labs/ai-gateway@latest"), None, None, None,
            "Native Go gateway. 30+ providers, 2500+ models. Caching, guardrails, cost controls.", "1.0.0",
            "https://github.com/ferro-labs/ai-gateway"),
        tc("summoned-gateway", "Summoned Gateway", ToolCategory::ApiGateway, ToolSource::Npm,
            Some("npm install @summoned/gateway"), Some("npx @summoned/gateway"), None, None,
            "Lightweight open-source gateway. Smart routing, auto-failover, response caching, cost governance.", "1.0.0",
            "https://github.com/summoned/gateway"),
        tc("pllm", "pLLM", ToolCategory::ApiGateway, ToolSource::Binary,
            Some("go install github.com/andreimerfu/pllm@latest"), None, None, None,
            "High-performance LLM gateway in Go. Adaptive routing, load balancing, auto failover.", "1.0.0",
            "https://github.com/andreimerfu/pllm"),
        tc("llmrouter", "LLMRouter", ToolCategory::ApiGateway, ToolSource::Pip,
            Some("pip install llmrouter-lib"), Some("llmrouter"), None, None,
            "Smart routing framework from UIUC. 16+ strategies: single-round, multi-round, personalization.", "0.3.1",
            "https://github.com/uiuc/llmrouter"),

        // ===== PROMPT OBFUSCATION (8) =====
        tc("velar", "Velar", ToolCategory::PromptObfuscation, ToolSource::Docker,
            Some("docker pull velar/velar"), Some("docker run -p 8080:8080 velar/velar"),
            Some("http://localhost:8080/health"), Some(8080),
            "Local Privacy Firewall. MITM proxy for AI traffic. Detects/scubs PII, replaces with fake tokens.", "1.0.0",
            "https://github.com/your/velar"),
        tc("megent", "megent", ToolCategory::PromptObfuscation, ToolSource::Pip,
            Some("pip install megent"), Some("megent"), None, None,
            "Open-source security middleware for AI agents. Prompt injection defense, tool allow/deny, data masking.", "1.0.0",
            "https://github.com/your/megent"),
        tc("prompt-demon", "Prompt-DEMON", ToolCategory::PromptObfuscation, ToolSource::Pip,
            Some("pip install prompt-demon"), Some("prompt-demon"), None, None,
            "Advanced prompt generation framework. Obfuscation, linguistic fusion, multi-layer bypass theory.", "1.0.0",
            "https://github.com/ShadowHackrs/prompt-generating"),
        tc("prompt-security", "PromptSecurity", ToolCategory::PromptObfuscation, ToolSource::Npm,
            Some("npm install @webling/promptsecurity"), Some("npx @webling/promptsecurity"), None, None,
            "Lightweight (~2ms/prompt) prompt sanitization. Rebuilds safe versions preserving style/constraints.", "1.0.0",
            "https://github.com/webling/promptsecurity"),
        tc("heretic", "Heretic", ToolCategory::PromptObfuscation, ToolSource::Pip,
            Some("pip install heretic-llm"), Some("heretic"), None, None,
            "Removes safety alignment from LLMs using directional ablation. No expensive retraining needed.", "1.0.0",
            "https://github.com/0xSojalSec/Uncensored-AI"),
        tc("wormgpt", "WormGPT 4", ToolCategory::PromptObfuscation, ToolSource::Pip,
            Some("pip install wormgpt"), Some("wormgpt"), None, None,
            "Uncensored LLM for automated text generation. Extended context, style control, obfuscated content.", "4.0.0",
            "https://github.com/wormGPT-jailbreak/wormGPT"),

        // ===== PROXY INFRASTRUCTURE (8) =====
        tc("proxybroker2", "ProxyBroker2", ToolCategory::ProxyInfrastructure, ToolSource::Docker,
            Some("docker pull bluet/proxybroker2"), Some("docker run --rm bluet/proxybroker2"),
            None, None,
            "Async proxy finder. Searches 50+ sources, finds 7000+ proxies. Rotating HTTP/SOCKS4/5 server.", "2.0.0",
            "https://github.com/bluet/proxybroker2"),
        tc("elfproxy", "ElfProxy", ToolCategory::ProxyInfrastructure, ToolSource::Mcp,
            Some("npx @elfproxy/proxy-pool-mcp-server"), Some("npx @elfproxy/proxy-pool-mcp-server"),
            None, None,
            "Global residential proxy infrastructure. 195+ countries, auto IP rotation (1s-24h), TLS masking.", "1.0.0",
            "https://github.com/elfproxy/proxy-pool-mcp-server"),
        tc("nyxproxy", "NyxProxy-OSS", ToolCategory::ProxyInfrastructure, ToolSource::Docker,
            Some("docker pull nyxproxy/nyxproxy"), Some("docker run nyxproxy/nyxproxy"), None, None,
            "High-performance IPv6 rotating proxy. Different IPv6 per request from /64 subnet. <100ms latency.", "1.0.0",
            "https://github.com/Jannik-Schroeder/nyxproxy-oss"),
        tc("go-proxy6", "go-proxy6", ToolCategory::ProxyInfrastructure, ToolSource::Docker,
            Some("docker-compose up -d"), Some("docker-compose up -d"), None, None,
            "High-performance IPv6-only HTTP/HTTPS proxy. 199,588 req/s throughput. Prevents IPv4 leaks.", "1.0.0",
            "https://github.com/your/go-proxy6"),
        tc("omniprox", "OmniProx", ToolCategory::ProxyInfrastructure, ToolSource::Pip,
            Some("pip install omniprox"), Some("omniprox"), None, None,
            "Multi-cloud HTTP proxy manager. GCP, Azure, Alibaba, CloudFlare. IP rotation + header manipulation.", "1.0.0",
            "https://github.com/ZephrFish/OmniProx"),
        tc("rotato", "rotato", ToolCategory::ApiGateway, ToolSource::Npm,
            Some("npm install -g rotato"), Some("rotato"), None, None,
            "API key rotator. Auto-rotates keys across providers (OpenAI, Gemini, OpenRouter, Groq) on 429 errors.", "1.0.0",
            "https://github.com/your/rotato"),
        tc("ai-edge", "ai-edge", ToolCategory::ProxyInfrastructure, ToolSource::Npm,
            Some("npm install ai-edge"), Some("ai-edge"), None, None,
            "Local LLM proxy. Distributes requests across backends with rate limiting and caching.", "1.0.0",
            "https://github.com/your/ai-edge"),
        tc("web-search-mcp-cloak", "web-search-mcp-cloak", ToolCategory::ProxyInfrastructure, ToolSource::Mcp,
            Some("npx web-search-mcp-cloak"), Some("npx web-search-mcp-cloak"), None, None,
            "Fork of web-search-mcp. Replaces Playwright with CloakBrowser + Webshare proxy rotation.", "1.0.0",
            "https://github.com/mrkrsl/web-search-mcp-cloak"),

        // ===== SWARM ORCHESTRATION (8) =====
        tc("ruflo", "Ruflo", ToolCategory::SwarmOrchestration, ToolSource::Npm,
            Some("npx ruflo init"), Some("npx ruflo start"), None, None,
            "Enterprise AI agent orchestration. 51k★ GitHub. 100+ agents, 60 commands, 30 skills, MCP server, self-learning memory.", "3.7.0",
            "https://github.com/ruvnet/ruflo"),
        tc("evonic", "Evonic", ToolCategory::SwarmOrchestration, ToolSource::Pip,
            Some("pip install evonic"), Some("evonic"), None, None,
            "Agent design, building, and orchestration framework. A2A communication, swarm creation.", "0.1.0",
            "https://github.com/anvie/evonic"),
        tc("clawteam", "ClawTeam", ToolCategory::SwarmOrchestration, ToolSource::Pip,
            Some("pip install clawteam"), Some("clawteam"), None, None,
            "CLI tool for creating agent teams. Leader agent spawns specialists, distributes tasks.", "0.1.0",
            "https://github.com/clawteam/clawteam"),
        tc("mission-control", "Mission Control", ToolCategory::SwarmOrchestration, ToolSource::Npm,
            Some("npm install -g mission-control"), Some("mission-control"), None, None,
            "Self-hosted dashboard for coordinating agent fleets, cost tracking, task management.", "1.0.0",
            "https://github.com/builderz-labs/mission-control"),
        tc("open-swarm", "Open Swarm", ToolCategory::SwarmOrchestration, ToolSource::Pip,
            Some("pip install open-swarm"), Some("open-swarm"), None, None,
            "Local coordinator for launching and monitoring software agent swarms from single interface.", "0.1.0",
            "https://github.com/openswarm-ai/openswarm"),
        tc("clawswarm", "ClawSwarm", ToolCategory::SwarmOrchestration, ToolSource::Docker,
            Some("docker pull 1panel/clawswarm"), Some("docker run -d --name=clawswarm 1panel/clawswarm"), None, None,
            "Open-source orchestration system for OpenClaw. Swarm intelligence via unified group chat.", "1.0.0",
            "https://github.com/clawswarm/clawswarm"),
        tc("openclaw-hawkins", "openclaw-hawkins", ToolCategory::SwarmOrchestration, ToolSource::Pip,
            Some("pip install openclaw-hawkins"), Some("openclaw-hawkins"), None, None,
            "Multi-agent orchestration (VINES + VECNA). 1 smart coordinator + 6 specialist agents.", "0.1.0",
            "https://github.com/parijatmukherjee/openclaw-hawkins"),
        tc("swarmkit", "swarmkit", ToolCategory::SwarmOrchestration, ToolSource::Npm,
            Some("npm install swarmkit"), Some("npx swarmkit"), None, None,
            "Toolkit for building, running, and optimizing multi-agent systems. Tasks, memory, learning.", "0.1.0",
            "https://github.com/swarmkit/swarmkit"),

        // ===== MONETIZATION (13) =====
        tc("cashclaw", "CashClaw", ToolCategory::Monetization, ToolSource::Npm,
            Some("npm install -g cashclaw-agent"), Some("cashclaw-agent"), None, None,
            "Autonomous agent that takes work, completes it, collects payment, learns. Connects to freelance markets.", "1.0.0",
            "https://github.com/cashclaw/cashclaw-agent"),
        tc("lucid-agents", "Lucid Agents", ToolCategory::Monetization, ToolSource::Npm,
            Some("bunx @lucid-agents/cli create"), Some("bunx @lucid-agents/cli"), None, None,
            "Framework + business model for building and deploying autonomous agents. On-chain identity, crypto payment.", "1.0.0",
            "https://github.com/lucid-agents/lucid-agents"),
        tc("arcwarden", "ArcWarden", ToolCategory::Monetization, ToolSource::Pip,
            Some("pip install arcwarden"), Some("arcwarden"), None, None,
            "Autonomous economic agent selling security services to other agents. USDC payments.", "0.1.0",
            "https://github.com/ibonon/Arcwarden"),
        tc("bitterbot", "Bitterbot Desktop", ToolCategory::Monetization, ToolSource::Npm,
            Some("npm install -g bitterbot"), Some("bitterbot"), None, None,
            "Local personal AI assistant. Biological memory, dream engine, P2P skill economy.", "0.1.0",
            "https://github.com/Bitterbot-AI/bitterbot-desktop"),
        tc("dgrid-arena", "DGrid Arena", ToolCategory::Monetization, ToolSource::Npm,
            Some("npm install -g dgrid"), Some("dgrid-arena"), None, None,
            "Connect your API keys to agent that auto-votes in model battles. Earn USDT 24/7.", "0.1.0",
            "https://dgrid.ai"),
        tc("ton-marketplace", "TON AI Agent Marketplace", ToolCategory::Monetization, ToolSource::Npm,
            Some("npm install -g ton-agent"), Some("ton-agent"), None, None,
            "Decentralized AI agent marketplace. Revenue sharing via smart contracts on TON.", "0.1.0",
            "https://ton.org/agent-marketplace"),
        tc("tether-wdk", "Tether WDK", ToolCategory::Monetization, ToolSource::Npm,
            Some("npm install @tether/wdk"), None, None, None,
            "Non-custodial multi-chain wallet SDK from Tether. Bitcoin, Ethereum, Solana, TON.", "1.0.0",
            "https://github.com/tether/wdk"),
        tc("alphawallet", "AlphaWallet", ToolCategory::Monetization, ToolSource::Npm,
            Some("npm install -g alphawallet"), Some("alphawallet"), None, None,
            "Self-custody Ethereum wallet. 100% open-source, customizable.", "1.0.0",
            "https://alphawallet.com"),
        tc("clear-evm", "Clear EVM Wallet", ToolCategory::Monetization, ToolSource::Npm,
            Some("npm install clear-evm-wallet"), None, None, None,
            "Lightweight open-source EVM wallet. Implements MetaMask API interface.", "0.1.0",
            "https://github.com/clear-evm/clear-evm-wallet"),
        tc("paypal-agent-toolkit", "PayPal Agent Toolkit", ToolCategory::Monetization, ToolSource::Pip,
            Some("pip install paypal-agent-toolkit"), Some("paypal-agent-toolkit"), None, None,
            "Python + TypeScript toolkit enabling agents to interact with PayPal APIs. 30+ operations via function calling.", "1.0.0",
            "https://github.com/paypal/paypal-agent-toolkit"),
        tc("paycrypt", "PayCrypt", ToolCategory::Monetization, ToolSource::Npm,
            Some("npm install -g paycrypt"), Some("paycrypt"), None, None,
            "AI-powered payment gateway integration code generator. Stripe, PayPal, Razorpay.", "1.0.0",
            "https://github.com/AmanYadav000/PayCrypt"),
        tc("braintree-mcp", "Braintree MCP Server", ToolCategory::Monetization, ToolSource::Mcp,
            Some("npx braintree-mcp"), Some("npx braintree-mcp"), None, None,
            "Unofficial MCP server for PayPal Braintree. Payment processing, customer management, transactions.", "0.1.0",
            "https://llmbase.ai/braintree-mcp"),

        // ===== OFFENSIVE CYBER (4) =====
        tc("transilience-ai", "Transilience AI Community Tools", ToolCategory::OffensiveCyber, ToolSource::Pip,
            Some("pip install transilience-ai"), Some("transilience-ai"), None, None,
            "26 skills + 3 open-source tools for Claude Code. Penetration testing and bug bounty automation. 100% CTF solve rate.", "1.0.0",
            "https://github.com/transilienceai/communitytools"),
        tc("threatswarm", "ThreatSwarm", ToolCategory::OffensiveCyber, ToolSource::Pip,
            Some("pip install threatswarm"), Some("threatswarm"), None, None,
            "27 AI agents managing complete kill chain with single command. Powered by 754 security skills.", "0.1.0",
            "https://github.com/mukul975/Threatswarm"),
        tc("metatron", "METATRON", ToolCategory::OffensiveCyber, ToolSource::Pip,
            Some("pip install metatron"), Some("metatron"), None, None,
            "Fully local penetration testing assistant. No cloud, no API keys, no subscriptions.", "0.1.0",
            "https://github.com/sooryathejas/METATRON"),
        tc("cyberstrike", "CyberStrike", ToolCategory::OffensiveCyber, ToolSource::Pip,
            Some("pip install cyberstrike"), Some("cyberstrike"), None, None,
            "First open-source offensive AI agent. Turns any LLM into autonomous red team.", "0.1.0",
            "https://github.com/CyberStrikeus/CyberStrike"),

        // ===== PROXY/IP ROTATION (new tools, 2) =====
        tc("termux-tor-rotator", "Termux-Tor-IP-Rotator", ToolCategory::ProxyIp, ToolSource::Pip,
            Some("pip install termux-tor-ip-rotator"), Some("termux-tor-ip-rotator"), None, None,
            "IP changer via Tor with auto-rotation. SOCKS5 + HTTP proxy at system level.", "1.0.0",
            "https://github.com/naborajs/Termux-Tor-IP-Rotator"),
        tc("aproxy", "aproxy", ToolCategory::ProxyIp, ToolSource::Binary,
            Some("go install github.com/ArnabXD/aproxy@latest"), None, None, None,
            "Anonymous proxy server. Lightweight and easy to deploy.", "0.1.0",
            "https://github.com/ArnabXD/aproxy"),

        // ===== IPv6 BLOCKS (additional, 3) =====
        tc("ipv6-dynamic-proxy", "ipv6-dynamic-proxy", ToolCategory::Ipv6Blocks, ToolSource::Docker,
            Some("docker pull ghcr.io/seongminhwan/ipv6-dynamic-proxy"),
            Some("docker run ghcr.io/seongminhwan/ipv6-dynamic-proxy"), None, None,
            "Multi-protocol dynamic proxy server (SOCKS5 + HTTP). Random IP per request. CIDR auth.", "1.0.0",
            "https://github.com/seongminhwan/ipv6-dynamic-proxy"),
        tc("http-proxy-ipv6-pool", "http-proxy-ipv6-pool", ToolCategory::Ipv6Blocks, ToolSource::Rust,
            Some("cargo install http-proxy-ipv6-pool"), None, None, None,
            "Each request from separate IPv6 address. Bypasses rate limits. Built in Rust (zu1k, 626★).", "0.1.0",
            "https://github.com/zu1k/http-proxy-ipv6-pool"),
        tc("auto-ipv6proxy", "Auto-ipv6Proxy", ToolCategory::Ipv6Blocks, ToolSource::Pip,
            Some("pip install auto-ipv6proxy"), Some("auto-ipv6proxy"), None, None,
            "One-command auto-install script for IPv6 proxy server.", "1.0.0",
            "https://github.com/layerweb/Auto-ipv6Proxy"),

        // ===== SSH & REMOTE DESKTOP (5) =====
        tc("nexterm", "Nexterm", ToolCategory::SshRemoteDesktop, ToolSource::Docker,
            Some("docker pull germannewsmaker/nexterm"),
            Some("docker run -d -p 6989:6989 germannewsmaker/nexterm"),
            Some("http://localhost:6989/health"), Some(6989),
            "Open-source server management. SSH, VNC, RDP, SFTP, Docker, Proxmox in single web dashboard.", "1.0.0",
            "https://github.com/nexterm/nexterm"),
        tc("lazyssh", "Lazyssh", ToolCategory::SshRemoteDesktop, ToolSource::Binary,
            Some("go install github.com/Adembc/lazyssh@latest"), Some("lazyssh"), None, None,
            "Interactive terminal SSH manager. Navigate, connect, manage, transfer files. Beautiful keyboard UI.", "1.0.0",
            "https://github.com/Adembc/lazyssh"),
        tc("ssh-pilot", "SSH Pilot", ToolCategory::SshRemoteDesktop, ToolSource::Binary,
            Some("go install github.com/mfat/sshpilot@latest"), Some("ssh-pilot"), None, None,
            "Modern cross-platform SSH connection manager. Termius/Putty alternative. Multi-tab, SFTP, port forwarding.", "1.0.0",
            "https://github.com/mfat/sshpilot"),
        tc("xpipe", "XPipe", ToolCategory::SshRemoteDesktop, ToolSource::Binary,
            Some("npm install -g xpipe"), Some("xpipe"), None, None,
            "Shell connection hub and remote file manager. Integrates with ssh, docker, kubectl, CLI tools.", "1.0.0",
            "https://github.com/xpipe-io/xpipe"),

        // ===== SERVER MANAGEMENT & MONITORING (5) =====
        tc("beszel", "Beszel", ToolCategory::ServerManagement, ToolSource::Docker,
            Some("docker pull beszel/beszel"), Some("docker run -d -p 8090:8090 beszel/beszel"),
            Some("http://localhost:8090/health"), Some(8090),
            "Lightweight server monitoring platform. Docker stats, historical data, alerts. Clean interface.", "1.0.0",
            "https://beszel.dev"),
        tc("1panel", "1Panel V2", ToolCategory::ServerManagement, ToolSource::Docker,
            Some("docker pull 1panel/1panel"), Some("docker run -d -p 8091:8091 1panel/1panel"),
            Some("http://localhost:8091/health"), Some(8091),
            "Modern Linux server management panel. Unified multi-server management, resource monitoring, file/container mgmt.", "1.0.0",
            "https://github.com/1Panel-dev/1Panel"),
        tc("apiary", "Apiary", ToolCategory::ServerManagement, ToolSource::Npm,
            Some("npm install -g apiary"), Some("apiary"), None, None,
            "⚠️ NOTE: npm 'apiary' is an API documentation CLI tool (2016). NOT a server management tool. Use Cronicle/XPipe instead.", "1.0.0",
            "https://apiary.io"),
        tc("cronicle", "Cronicle", ToolCategory::ServerManagement, ToolSource::Docker,
            Some("docker pull cronicle/cronicle"), Some("docker run -d -p 3012:3012 cronicle/cronicle"),
            Some("http://localhost:3012/health"), Some(3012),
            "Multi-server task scheduler with web UI. Auto-failover, near-server discovery, webhook support.", "1.0.0",
            "https://github.com/jhuckaby/Cronicle"),
        tc("mcp-server-manager", "MCP Server Manager", ToolCategory::ServerManagement, ToolSource::Binary,
            Some("go install github.com/vlazic/mcp-server-manager@latest"), Some("mcp-server-manager"), None, None,
            "Cross-platform MCP server manager in single Go binary. Interactive HTMX web interface.", "1.0.0",
            "https://github.com/vlazic/mcp-server-manager"),

        // ===== AI PROVIDER INTEGRATION TOOLS (5) =====
        tc("aisuite", "aisuite", ToolCategory::AiProviderIntegration, ToolSource::Pip,
            Some("pip install aisuite[all]"), Some("aisuite"), None, None,
            "Unified Python API from Andrew Ng. OpenAI, Anthropic, Google, Hugging Face, AWS, Cohere, Mistral, Ollama.", "1.0.0",
            "https://github.com/andrewng/aisuite"),
        tc("conduit-llm", "ConduitLLM", ToolCategory::AiProviderIntegration, ToolSource::Npm,
            Some("npm install @knn_labs/conduit-gateway-client"), Some("npx conduit"), None, None,
            "Unified API gateway for multiple LLM providers. OpenAI-compatible endpoints. 10,000+ concurrent sessions.", "1.0.0",
            "https://github.com/knn-labs/conduit-llm"),
        tc("any-llm", "any-llm", ToolCategory::AiProviderIntegration, ToolSource::Pip,
            Some("pip install any-llm"), Some("any-llm"), None, None,
            "Open-source Python library from Mozilla.ai. Switch between cloud/local providers without rewriting code.", "0.1.0",
            "https://github.com/mozilla/any-llm"),
        tc("litellm", "LiteLLM", ToolCategory::AiProviderIntegration, ToolSource::Pip,
            Some("pip install litellm"), Some("litellm"), None, None,
            "Mature library with unified interface for 100+ LLMs. OpenAI, Claude, Gemini, Cohere, and more.", "1.0.0",
            "https://github.com/BerriAI/litellm"),
        tc("monollm", "monollm", ToolCategory::AiProviderIntegration, ToolSource::Pip,
            Some("pip install monollm"), Some("monollm"), None, None,
            "Framework with unified interface for multiple LLM providers. Modern Python async/await patterns.", "0.1.0",
            "https://github.com/monollm/monollm"),

        // ===== COMMUNICATION PLATFORMS (platform entries, 28) =====
        tc("telegram-bot", "Telegram Bot", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Telegram integration via long polling/webhook. Full message send/receive.", "1.0.0",
            "https://core.telegram.org/bots/api"),
        tc("discord-bot", "Discord Bot", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Discord integration via WebSocket Gateway. Full bot API support.", "1.0.0",
            "https://discord.com/developers/docs"),
        tc("slack-bot", "Slack Bot", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Slack integration via Socket Mode / HTTP. Messaging and file sharing.", "1.0.0",
            "https://api.slack.com"),
        tc("whatsapp-bot", "WhatsApp Bot", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "WhatsApp integration via WebSocket QR pairing. Message send/receive.", "1.0.0",
            "https://developers.facebook.com/docs/whatsapp"),
        tc("signal-bot", "Signal Bot", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Signal integration. End-to-end encrypted messaging.", "1.0.0",
            "https://signal.org/docs"),
        tc("imessage-bot", "iMessage Bot", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "iMessage integration for Apple ecosystem.", "1.0.0",
            "https://developer.apple.com/documentation/usernotifications"),
        tc("google-chat", "Google Chat", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Google Chat via HTTP webhook integration.", "1.0.0",
            "https://developers.google.com/chat"),
        tc("microsoft-teams", "Microsoft Teams", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Microsoft Teams via webhook/proactive messaging. Full message support.", "1.0.0",
            "https://learn.microsoft.com/en-us/microsoftteams/platform"),
        tc("line", "LINE", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "LINE messaging platform via webhook integration.", "1.0.0",
            "https://developers.line.biz"),
        tc("irc", "IRC", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Internet Relay Chat protocol integration. Channel messaging.", "1.0.0",
            "https://ircv3.net"),
        tc("matrix", "Matrix", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Matrix protocol integration. Decentralized, encrypted messaging.", "1.0.0",
            "https://matrix.org"),
        tc("mattermost", "Mattermost", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Mattermost via webhook/bot API. Team communication.", "1.0.0",
            "https://developers.mattermost.com"),
        tc("email", "Email (SMTP/IMAP)", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Email integration via SMTP/IMAP. Send and receive emails.", "1.0.0",
            "https://www.rfc-editor.org/rfc/rfc5321"),
        tc("sms", "SMS (Twilio)", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "SMS messaging via Twilio API. Send and receive text messages.", "1.0.0",
            "https://www.twilio.com/docs"),
        tc("home-assistant", "Home Assistant", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Home Assistant integration via webhook. Smart home control.", "1.0.0",
            "https://developers.home-assistant.io"),
        tc("dingtalk", "DingTalk", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "DingTalk integration with full feature support. Chinese enterprise communication.", "1.0.0",
            "https://open.dingtalk.com"),
        tc("feishu", "Feishu/Lark", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Feishu/Lark integration with full feature support. Enterprise collaboration.", "1.0.0",
            "https://open.feishu.cn"),
        tc("wecom", "WeCom (企业微信)", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "WeCom integration. EAS + Callback modes. Enterprise WeChat.", "1.0.0",
            "https://developer.work.weixin.qq.com"),
        tc("wechat", "WeChat/Weixin", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "WeChat via iLink Bot API (QR scan pairing). Personal WeChat automation.", "1.0.0",
            "https://www.wechat.com"),
        tc("qq", "QQ/QQBot", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "QQ bot integration via QQ Bot API. Chinese social platform.", "1.0.0",
            "https://bot.q.qq.com"),
        tc("yuanbao", "Yuanbao (元宝)", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Yuanbao integration via Yuanbao API. Tencent AI assistant platform.", "1.0.0",
            "https://yuanbao.tencent.com"),
        tc("webhook-generic", "Webhook", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Generic webhook integration. Send/receive HTTP callbacks.", "1.0.0",
            "https://webhooks.dev"),
        tc("api-server", "API Server", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "REST API server for external integrations.", "1.0.0",
            "https://restfulapi.net"),
        tc("webchat", "WebChat", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Embedded web chat via WebSocket. Real-time browser-based messaging.", "1.0.0",
            "https://websocket.org"),
        tc("cli-terminal", "CLI Terminal", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Command-line interface for direct terminal interaction.", "1.0.0",
            "https://en.wikipedia.org/wiki/Command-line_interface"),
        tc("web-ui", "Web UI", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Web dashboard control panel. Full management interface.", "1.0.0",
            "https://en.wikipedia.org/wiki/Web_application"),
        tc("cron-jobs", "Cron Jobs", ToolCategory::CommunicationPlatform, ToolSource::BuiltIn,
            None, None, None, None,
            "Scheduled tasks with delivery.channel support. Cron-based automation.", "1.0.0",
            "https://en.wikipedia.org/wiki/Cron"),

        // ===== COMMUNICATION TOOLS (6) =====
        tc("tgmcp", "TGMCP", ToolCategory::CommunicationPlatform, ToolSource::Pip,
            Some("pip install tgmcp"), Some("tgmcp"), None, None,
            "MCP bridge between AI agents and Telegram. 73+ Telegram operations as MCP tools.", "1.0.0",
            "https://github.com/tgmcp/tgmcp"),
        tc("jarvis-bot", "Jarvis Bot", ToolCategory::CommunicationPlatform, ToolSource::Pip,
            Some("pip install jarvis-bot"), Some("jarvis-bot"), None, None,
            "Private remote control bot via Telegram. Screenshots, shutdown, mouse, click.", "0.1.0",
            "https://github.com/Artin-khodayari/Jarvis-bot"),
        tc("ai-in-shell", "AI-in-Shell", ToolCategory::CommunicationPlatform, ToolSource::Pip,
            Some("pip install ai-in-shell"), Some("ai-in-shell"), None, None,
            "Linux remote management agent via Telegram. Secure bridge between chat and Linux machine.", "0.1.0",
            "https://github.com/ai-in-shell/ai-in-shell"),
        tc("pybotnet", "PyBotNet", ToolCategory::CommunicationPlatform, ToolSource::Pip,
            Some("pip install pybotnet"), Some("pybotnet"), None, None,
            "Python framework for building remote control botnets. Agents execute commands from central dashboard.", "1.0.0",
            "https://github.com/onionj/pybotnet"),
        tc("whatsapp-ai-framework", "WhatsApp AI Framework", ToolCategory::CommunicationPlatform, ToolSource::Npm,
            Some("npm install whatsapp-ai-framework"), Some("npx whatsapp-ai-framework"), None, None,
            "Production-ready WhatsApp automation. Ban protection, n8n AI integration, RAG support.", "1.0.0",
            "https://github.com/cloud8877-source/whatsapp-ai-framework"),
        tc("neonize-whatsapp", "Neonize + whatsmeow", ToolCategory::CommunicationPlatform, ToolSource::Binary,
            Some("go install github.com/adityapatil123/whatsapp-bot-example@latest"), None, None, None,
            "Multi-session WhatsApp bot. whatsmeow native Go library. 10-20MB per session.", "1.0.0",
            "https://github.com/adityapatil123/whatsapp-bot-example"),

        // ===== MCP SERVERS & SKILLS (4) =====
        tc("agentql-mcp", "AgentQL MCP", ToolCategory::McpSkills, ToolSource::Mcp,
            Some("npx @agentql/mcp-server"), Some("npx @agentql/mcp-server"), None, None,
            "MCP server for extracting structured data from unstructured web pages.", "1.0.0",
            "https://github.com/agentql/mcp-server"),
        tc("zeromcp", "ZeroMCP", ToolCategory::McpSkills, ToolSource::Pip,
            Some("pip install zeromcp"), Some("zeromcp"), None, None,
            "Minimal MCP server in pure Python. Zero external dependencies.", "0.1.0",
            "https://github.com/mrexodia/zeromcp"),
        tc("mcp-jupyter", "mcp-jupyter", ToolCategory::McpSkills, ToolSource::Pip,
            Some("pip install mcp-jupyter"), Some("mcp-jupyter"), None, None,
            "MCP server giving coding agents access to live Jupyter kernel state (Block Inc., 42★).", "0.1.0",
            "https://github.com/block/mcp-jupyter"),
        tc("notebooklm-mcp", "NotebookLM MCP", ToolCategory::McpSkills, ToolSource::Npm,
            Some("npx notebooklm-mcp"), Some("npx notebooklm-mcp"), None, None,
            "MCP server connecting to Google NotebookLM from any MCP client (2.4k★).", "1.0.0",
            "https://github.com/PleasePrompto/notebooklm-mcp"),

        // ===== INFRASTRUCTURE (3) =====
        tc("docker", "Docker", ToolCategory::Infrastructure, ToolSource::Docker,
            Some("curl -fsSL https://get.docker.com | sh"), Some("docker"),
            Some("http://localhost:2375/health"), Some(2375),
            "Container platform. Isolate each agent in its own container.", "24.0.0",
            "https://docker.com"),
        tc("kubernetes", "Kubernetes", ToolCategory::Infrastructure, ToolSource::Binary,
            Some("curl -LO https://dl.k8s.io/release/stable.txt/bin/windows/amd64/kubectl.exe"),
            Some("kubectl"), Some("https://kubernetes.io"), None,
            "Container orchestration for hundreds of containers. Supported by CloakBrowser Manager.", "1.29.0",
            "https://kubernetes.io"),
        tc("n8n", "n8n (Community Edition)", ToolCategory::Infrastructure, ToolSource::Docker,
            Some("docker pull n8nio/n8n"), Some("docker run -d -p 5678:5678 n8nio/n8n"),
            Some("http://localhost:5678/health"), Some(5678),
            "Workflow automation between agents and tools. Visual builder with HTTP/node integrations.", "1.0.0",
            "https://n8n.io"),

        // ===== SEARCH ENGINE (10) =====
        tc("searxng", "SearXNG", ToolCategory::SearchEngine, ToolSource::Docker,
            Some("docker pull searxng/searxng"),
            Some("docker run -d --name searxng -p 8080:8080 searxng/searxng"),
            Some("http://localhost:8080/health"), Some(8080),
            "Metasearch engine aggregating 230+ backends. Clean JSON API. AGPL-3.0.", "2025.0.0",
            "https://github.com/searxng/searxng"),
        tc("agentsearch", "AgentSearch", ToolCategory::SearchEngine, ToolSource::Pip,
            Some("pip install agent-search"), Some("python -c \"from agent_search import SciPhi\""), None, None,
            "Framework for powering search agents with RAG. Integrates LLMs with multiple search engines. MIT.", "1.0.0",
            "https://github.com/SciPhi-AI/agent-search"),
        tc("wuxing-search-mcp", "Wuxing Search MCP", ToolCategory::SearchEngine, ToolSource::Mcp,
            Some("git clone https://github.com/MaesHughes/wuxing-search-mcp.git && cd wuxing-search-mcp && npm install"),
            Some("node src/index.js"), None, None,
            "SearXNG-based MCP aggregating 100+ search engines. Bilingual zh/en. MIT.", "1.0.0",
            "https://github.com/MaesHughes/wuxing-search-mcp"),
        tc("one-search-mcp", "one-search-mcp", ToolCategory::SearchEngine, ToolSource::Npm,
            Some("npm install -g one-search-mcp"), Some("npx -y one-search-mcp"), None, None,
            "Unified MCP server: SearXNG + Tavily + DuckDuckGo + Bing + Google + Zhipu + Exa + Bocha. MIT.", "1.0.0",
            "https://github.com/yokingma/one-search-mcp"),
        tc("open-websearch", "open-webSearch", ToolCategory::SearchEngine, ToolSource::Npm,
            Some("npm install -g open-websearch"), Some("npx open-websearch@latest"), None, None,
            "Multi-engine search MCP. No API keys needed. Bing, Baidu, DDG, Brave, Exa, GitHub, Juejin, CSDN. MIT.", "1.0.0",
            "https://github.com/Aas-ee/open-webSearch"),
        tc("anysearch-mcp", "AnySearch MCP Server", ToolCategory::SearchEngine, ToolSource::Mcp,
            Some("npx -y mcp-remote https://api.anysearch.com/mcp"), Some("npx -y mcp-remote https://api.anysearch.com/mcp"), None, None,
            "Unified real-time search MCP. 23 vertical domains (medical, legal, code, academic). Cloud API.", "1.0.0",
            "https://github.com/anysearch-ai/anysearch-mcp"),
        tc("mcp-local-rag", "mcp-local-rag", ToolCategory::SearchEngine, ToolSource::Npm,
            Some("npx -y mcp-local-rag"), Some("npx mcp-local-rag"), None, None,
            "Local-first RAG MCP server with semantic + keyword search. Zero setup, fully private. MIT.", "1.0.0",
            "https://github.com/shinpr/mcp-local-rag"),
        tc("websurfx", "Websurfx", ToolCategory::SearchEngine, ToolSource::Binary,
            Some("cargo install websurfx"), Some("websurfx"),
            Some("http://localhost:8088/health"), Some(8088),
            "Rust metasearch engine. io-uring, lightning-fast, privacy-respecting. AGPLv3.", "1.0.0",
            "https://github.com/neon-mmd/websurfx"),
        tc("vane", "Vane (Perplexica)", ToolCategory::SearchEngine, ToolSource::Docker,
            Some("docker pull itzcrazykns1337/vane:latest"),
            Some("docker run -d -p 3000:3000 -v vane-data:/home/vane/data --name vane itzcrazykns1337/vane:latest"),
            Some("http://localhost:3000/health"), Some(3000),
            "AI-powered answer engine. Reads web directly, cites sources. Forked from Perplexica. 34k★. MIT.", "1.0.0",
            "https://github.com/ItzCrazyKns/Vane"),
        tc("yacy", "YaCy", ToolCategory::SearchEngine, ToolSource::Docker,
            Some("docker pull yacy/yacy_search_server:latest"),
            Some("docker run -d --name yacy -p 8090:8090 -p 8443:8443 yacy/yacy_search_server:latest"),
            Some("http://localhost:8090/health"), Some(8090),
            "P2P decentralized search. Every user runs a node. GPL-2.0.", "1.0.0",
            "https://github.com/yacy/yacy_search_server"),

        // ===== CONTENT FETCHING (3) =====
        tc("jina-reader", "Jina Reader", ToolCategory::ContentFetching, ToolSource::BuiltIn,
            None, None, None, None,
            "Free API — prepend r.jina.ai to any URL to get clean Markdown. No install needed.", "1.0.0",
            "https://jina.ai/reader/"),
        tc("crawl4ai", "Crawl4AI", ToolCategory::ContentFetching, ToolSource::Pip,
            Some("pip install crawl4ai"), Some("crawl4ai"), None, None,
            "Open-source web crawler. Structured extraction for RAG. Apache 2.0.", "1.0.0",
            "https://github.com/unclecode/crawl4ai"),
        tc("fetch-mcp", "Fetch MCP Server", ToolCategory::ContentFetching, ToolSource::Npm,
            Some("npm install -g mcp-fetch-server"), Some("npx mcp-fetch-server"), None, None,
            "MCP server fetching web pages as HTML/Markdown/text/JSON/YouTube transcripts. MIT.", "1.0.0",
            "https://github.com/zcaceres/fetch-mcp"),

        // ===== EMBEDDINGS / VECTOR DB (5) =====
        tc("bge-m3", "BGE-M3", ToolCategory::EmbeddingsVectorDb, ToolSource::Pip,
            Some("pip install FlagEmbedding"), None, None, None,
            "Multilingual embedding model. 100+ languages, 8192 tokens, dense+sparse+multi-vector. MIT.", "1.0.0",
            "https://huggingface.co/BAAI/bge-m3"),
        tc("wholembed-v3", "Wholembed v3", ToolCategory::EmbeddingsVectorDb, ToolSource::Pip,
            Some("pip install mixedbread"), None, None, None,
            "Omnimodal multilingual late-interaction retrieval. Beats BM25 on LIMIT benchmark. API-based.", "1.0.0",
            "https://mixedbread.com/blog/wholembed-v3"),
        tc("tobi-qmd", "tobi/qmd", ToolCategory::EmbeddingsVectorDb, ToolSource::Npm,
            Some("npm install -g qmd"), Some("qmd"), None, None,
            "Local CLI search engine for markdown. BM25 + vector + LLM reranking + MCP server. By Shopify founder.", "1.0.0",
            "https://github.com/tobi/qmd"),
        tc("qdrant", "Qdrant", ToolCategory::EmbeddingsVectorDb, ToolSource::Docker,
            Some("docker pull qdrant/qdrant"),
            Some("docker run -d --name qdrant -p 6333:6333 qdrant/qdrant"),
            Some("http://localhost:6333/health"), Some(6333),
            "Vector database in Rust. High-performance. Apache 2.0.", "1.0.0",
            "https://github.com/qdrant/qdrant"),
        tc("sqlite-vec", "SQLite-vec", ToolCategory::EmbeddingsVectorDb, ToolSource::Pip,
            Some("pip install sqlite-vec"), None, None, None,
            "Vector search inside SQLite. Drop-in vec0 extension. MIT.", "1.0.0",
            "https://github.com/asg017/sqlite-vec"),

        // ===== MEMORY / KNOWLEDGE GRAPH (8) =====
        tc("memoryos", "MemoryOS", ToolCategory::MemoryGraph, ToolSource::Pip,
            Some("git clone https://github.com/BAI-LAB/MemoryOS.git && pip install -r MemoryOS/requirements.txt"),
            None, None, None,
            "Memory OS: temporal graph + hybrid retrieval + Ebbinghaus decay. 78ms queries. EMNLP 2025 Oral.", "1.0.0",
            "https://github.com/BAI-LAB/MemoryOS"),
        tc("hermes-memory", "Hermes Agent Memory", ToolCategory::MemoryGraph, ToolSource::Pip,
            Some("pip install hermes-agent"), Some("hermes setup"), None, None,
            "Persistent memory via MEMORY.md/USER.md + SQLite FTS5 + vector search + 8 provider plugins. MIT.", "1.0.0",
            "https://github.com/NousResearch/hermes-agent"),
        tc("mem0", "Mem0", ToolCategory::MemoryGraph, ToolSource::Pip,
            Some("pip install mem0ai"), None, None, None,
            "Intelligent agent memory that learns user preferences. Python sidecar. Apache 2.0.", "1.0.0",
            "https://github.com/mem0ai/mem0"),
        tc("graphiti", "Graphiti", ToolCategory::MemoryGraph, ToolSource::Pip,
            Some("pip install graphiti-core"), None, None, None,
            "Temporal knowledge graph for AI agents. Neo4j/FalkorDB backend. 26k★. MCP server available.", "1.0.0",
            "https://github.com/getzep/graphiti"),
        tc("knowhere", "Knowhere", ToolCategory::MemoryGraph, ToolSource::Pip,
            Some("pip install knowhere"), None, None, None,
            "Vector search engine (Milvus). FAISS + HNSW + DiskANN. Also document parsing/RAG pipeline.", "1.0.0",
            "https://github.com/zilliztech/knowhere"),
        tc("neo4j", "Neo4j Community", ToolCategory::MemoryGraph, ToolSource::Docker,
            Some("docker pull neo4j:community"),
            Some("docker run -d --name neo4j -p 7474:7474 -p 7687:7687 neo4j:community"),
            Some("http://localhost:7474/health"), Some(7474),
            "Leading graph database. Cypher query language. GPL-3.0.", "5.0.0",
            "https://neo4j.com"),
        tc("dkg-v9", "DKG v9 (OriginTrail)", ToolCategory::MemoryGraph, ToolSource::Docker,
            Some("docker pull origintrail/dkg-node"),
            Some("docker run -d --name dkg-node origintrail/dkg-node"), None, None,
            "Decentralized Knowledge Graph. Verifiable assets on blockchain + graph DB. MIT.", "9.0.0",
            "https://github.com/OriginTrail"),
        tc("sibyl", "Sibyl", ToolCategory::MemoryGraph, ToolSource::Pip,
            Some("pip install sibyl-core"), None, None, None,
            "Collective intelligence runtime. Knowledge graph + persistent memory + agent orchestration. MIT.", "1.0.0",
            "https://github.com/hyperb1iss/sibyl"),

        // ===== LOCAL MODELS (4) =====
        tc("ollama", "Ollama", ToolCategory::LocalModels, ToolSource::Binary,
            Some("curl -fsSL https://ollama.com/install.sh | sh"), Some("ollama"),
            Some("http://localhost:11434/health"), Some(11434),
            "Local model runtime. Supports BGE-M3, Psyche-R1, and 100k+ models. MIT.", "0.5.0",
            "https://github.com/ollama/ollama"),
        tc("llamacpp", "llama.cpp", ToolCategory::LocalModels, ToolSource::Binary,
            Some("git clone https://github.com/ggml-org/llama.cpp && cd llama.cpp && make"),
            Some("./main"), None, None,
            "C++ model runtime. Higher CPU perf than Ollama. GGUF format. MIT.", "1.0.0",
            "https://github.com/ggml-org/llama.cpp"),
        tc("psyche-r1", "Psyche-R1", ToolCategory::LocalModels, ToolSource::Binary,
            Some("ollama pull psyche-r1"), None, None, None,
            "Psychological reasoning LLM (Qwen2.5-7B). Empathy + expertise + logic. 100% local.", "1.0.0",
            "https://huggingface.co/MindIntLab/Psyche-R1"),
        tc("openseeker", "OpenSeeker", ToolCategory::LocalModels, ToolSource::Binary,
            Some("pip install git+https://github.com/PolarSeeker/OpenSeeker.git"), None, None, None,
            "Search agent Qwen3-30B. SOTA on BrowseComp-ZH. Fully open training data.", "1.0.0",
            "https://github.com/PolarSeeker/OpenSeeker"),

        // ===== AGENT ORCHESTRATION (6) =====
        tc("deepagents", "DeepAgents", ToolCategory::AgentOrchestration, ToolSource::Pip,
            Some("pip install deepagents"), None, None, None,
            "Agent harness by LangChain. Planner + subagents + filesystem access. 22.8k★. MIT.", "1.0.0",
            "https://github.com/langchain-ai/deepagents"),
        tc("crewai", "CrewAI", ToolCategory::AgentOrchestration, ToolSource::Pip,
            Some("pip install crewai"), None, None, None,
            "Multi-agent framework. Roles + tasks + processes. Python sidecar. MIT.", "1.0.0",
            "https://github.com/crewAIInc/crewAI"),
        tc("autogen", "AutoGen (Microsoft)", ToolCategory::AgentOrchestration, ToolSource::Pip,
            Some("pip install pyautogen"), None, None, None,
            "Multi-agent conversations. Group chat, code execution. By Microsoft Research. MIT.", "1.0.0",
            "https://github.com/microsoft/autogen"),
        tc("openhands", "OpenHands", ToolCategory::AgentOrchestration, ToolSource::Docker,
            Some("docker pull ghcr.io/openhands/openhands"),
            Some("docker run -d -p 3001:3000 --privileged ghcr.io/openhands/openhands"),
            None, Some(3001),
            "Autonomous coding agent. Writes, tests, debugs code independently. MIT.", "1.0.0",
            "https://github.com/All-Hands-AI/OpenHands"),
        tc("aider", "Aider", ToolCategory::AgentOrchestration, ToolSource::Pip,
            Some("pip install aider-chat"), Some("aider"), None, None,
            "AI pair programming. Edits multiple files, git-aware. Apache 2.0.", "1.0.0",
            "https://github.com/paul-gauthier/aider"),
        tc("tabby", "Tabby", ToolCategory::AgentOrchestration, ToolSource::Docker,
            Some("docker pull tabbyml/tabby"),
            Some("docker run -d -p 8080:8080 tabbyml/tabby"),
            Some("http://localhost:8080/health"), Some(8080),
            "Self-hosted GitHub Copilot alternative. Code completion engine. Apache 2.0.", "1.0.0",
            "https://github.com/TabbyML/tabby"),

        // ===== RAG ENGINE (3) =====
        tc("ragflow", "RAGFlow", ToolCategory::RagEngine, ToolSource::Docker,
            Some("docker pull infiniflow/ragflow"),
            Some("docker run -d -p 9380:9380 infiniflow/ragflow"),
            Some("http://localhost:9380/health"), Some(9380),
            "Advanced RAG engine. Complex extraction. 20+ document types. Apache 2.0.", "1.0.0",
            "https://github.com/infiniflow/ragflow"),
        tc("llamaindex", "LlamaIndex", ToolCategory::RagEngine, ToolSource::Pip,
            Some("pip install llama-index"), None, None, None,
            "Advanced RAG framework. 40+ data source connectors. Python sidecar. MIT.", "1.0.0",
            "https://github.com/run-llama/llama_index"),
        tc("anythingllm", "AnythingLLM", ToolCategory::RagEngine, ToolSource::Docker,
            Some("docker pull mintplexlabs/anythingllm"),
            Some("docker run -d -p 3001:3001 mintplexlabs/anythingllm"),
            Some("http://localhost:3001/health"), Some(3001),
            "Full local RAG. UI + database + models. Document intelligence module. MIT.", "1.0.0",
            "https://github.com/Mintplex-Labs/anything-llm"),

        // ===== REFERENCE UI (2) =====
        tc("openwebui", "OpenWebUI", ToolCategory::ReferenceUi, ToolSource::Docker,
            Some("docker pull ghcr.io/open-webui/open-webui"),
            Some("docker run -d -p 3000:8080 ghcr.io/open-webui/open-webui"),
            Some("http://localhost:3000/health"), Some(3000),
            "Beautiful Ollama chat UI. For design inspiration only. MIT.", "1.0.0",
            "https://github.com/open-webui/open-webui"),
        tc("lobechat", "LobeChat", ToolCategory::ReferenceUi, ToolSource::Docker,
            Some("docker pull lobehub/lobe-chat"),
            Some("docker run -d -p 3210:3210 lobehub/lobe-chat"),
            Some("http://localhost:3210/health"), Some(3210),
            "Modern chat UI with MCP support. Multi-model. Plugin system inspiration. MIT.", "1.0.0",
            "https://github.com/lobehub/lobe-chat"),

        // ===== MCP SERVERS (5) =====
        tc("brave-search-mcp", "Brave Search MCP", ToolCategory::McpSkills, ToolSource::Mcp,
            Some("npx -y @modelcontextprotocol/server-brave-search"),
            Some("npx -y @modelcontextprotocol/server-brave-search"), None, None,
            "Web + local search via Brave Search API. By Anthropic reference. Requires BRAVE_API_KEY.", "1.0.0",
            "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search"),
        tc("puppeteer-mcp", "Puppeteer MCP Server", ToolCategory::McpSkills, ToolSource::Mcp,
            Some("npx -y @modelcontextprotocol/server-puppeteer"),
            Some("npx -y @modelcontextprotocol/server-puppeteer"), None, None,
            "Browser automation via Puppeteer. Navigate, screenshot, click, fill. Needs Chrome.", "1.0.0",
            "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer"),
        tc("gitlab-mcp", "GitLab MCP Server", ToolCategory::McpSkills, ToolSource::Mcp,
            Some("npx -y gitlab-mcp@latest"),
            Some("npx -y gitlab-mcp@latest"), None, None,
            "GitLab integration. 80+ tools: projects, MRs, issues, pipelines, wikis, releases. OAuth 2.0.", "1.0.0",
            "https://github.com/mcpland/gitlab-mcp"),
        tc("postgresql-mcp", "PostgreSQL MCP Server", ToolCategory::McpSkills, ToolSource::Mcp,
            Some("npx mcp-postgres-server"),
            Some("npx mcp-postgres-server"), None, None,
            "PostgreSQL database operations via MCP. Query, execute, list schemas/tables.", "1.0.0",
            "https://github.com/antonorlov/mcp-postgres-server"),
        tc("sqlite-mcp", "SQLite MCP Server", ToolCategory::McpSkills, ToolSource::Mcp,
            Some("npx -y @modelcontextprotocol/server-sqlite"),
            Some("npx -y @modelcontextprotocol/server-sqlite <path-to-db>"), None, None,
            "SQLite database analysis via MCP. Anthropic reference server. Query + analyze.", "1.0.0",
            "https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite"),
    ]
}
